### ISSUE TITLE
Some unhandled exception about thread

### ISSUE THREAD

**Issue by Jueast** [yangl1996/mini-chatter#21]
When close the client's window, the IDLE report the error below.
`>>> Unhandled exception in thread started by <bound method StartingPage.threading_receive of <__main__.StartingPage object at 0x0000000003459C18>>
Traceback (most recent call last):
  File "D:\Documents\GitHub\mini-chatter\tk_client.py", line 140, in threading_receive
    self.handle_exit(buffer)
  File "D:\Documents\GitHub\mini-chatter\tk_client.py", line 88, in handle_exit
    self.update_server_info(raw_string[6:])
  File "D:\Documents\GitHub\mini-chatter\tk_client.py", line 150, in update_server_info
    self.server_info[0].configure(text=infoContent[0])
  File "D:\Code\Python34\lib\tkinter\__init__.py", line 1319, in configure
    return self._configure('configure', cnf, kw)
  File "D:\Code\Python34\lib\tkinter\__init__.py", line 1310, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
RuntimeError: main thread is not in main loop`

**Comment by Jueast** [comment]
test environment: win7 64bit

**Comment by yangl1996** [comment]
may get fixed in 2b39fdc9f96fa43f0e814381361807cde326b3ac
